### ISSUE TITLE
Default Android App-Icon

### ISSUE THREAD

**Issue by SeefriedNoah** [RSHerrieden/AndroidApp#1]
The icon of the app is not the specified RSH logo, but the standard icon android icon if no own one has been set.

That happens only with the OnePlus Launcher.

**Comment by frommMoritz** [comment]
fixed in aff9d49e59b66eec7aa2cd84b449b418cbd1d0ff
Working with oneplus launcher on Oneplus 5t with Android 8.0 and Oxygen OS version 5.0.3
